export const GET_DEVELOPER = 'GET_DEVELOPER';
export const GET_DEVELOPER_FULFILLED = 'GET_DEVELOPER_FULFILLED';
export const GET_DEVELOPER_REJECTED = 'GET_DEVELOPER_REJECTED';

export const GET_DEVELOPERS = 'GET_DEVELOPERS';
export const GET_DEVELOPERS_FULFILLED = 'GET_DEVELOPERS_FULFILLED';
export const GET_DEVELOPERS_REJECTED = 'GET_DEVELOPERS_REJECTED';
