const NAMESPACE = 'DEVELOPERS';

export const GET_DEVELOPERS = `${NAMESPACE}/GET_ORDERS`;
export const GET_DEVELOPERS_SUCCESS = `${NAMESPACE}/GET_ORDERS_SUCCESS`;
export const GET_DEVELOPERS_FAIL = `${NAMESPACE}/GET_ORDERS_FAIL`;
