export const GET_POST = 'GET_POST';
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POST_REJECTED = 'GET_POST_REJECTED';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED';

export const GET_POSTS_BY_DEVELOPER_ID = 'GET_POSTS_BY_DEVELOPER_ID';
export const GET_POSTS_BY_DEVELOPER_ID_FULFILLED = 'GET_POSTS_BY_DEVELOPER_ID_FULFILLED';
export const GET_POSTS_BY_DEVELOPER_ID_REJECTED = 'GET_POSTS_BY_DEVELOPER_ID_REJECTED';
